#!/bin/bash
if [ -z "$1" ]; then
	echo "Expected directory name"
	exit 1
fi
if [ ! -d "$1" ]; then
	echo "Directory: $1 do not exist"
	exit 1
fi
if [ ! -f "$1/Dockerfile" ]; then
	echo "Dockerfile in directory: $1 do not exist"
	exit 1
fi
export commandName="$1"
